title: International Thwaites Glacier Collaboration field and ship best practices 
description: This document is intended to be an ongoing collaborative effort across the polar science community. All feedback and edits are welcome. Follow the GitHub link below to contribute. 
theme: jekyll-theme-midnight

