title: International Thwaites Glacier Collaboration field and ship best practices
description: This document is intended to be an ongoing collaborative effort across the polar science community. All feedback and edits are welcome. Follow the GitHub link above for information on how to contribute to and cite this document.
theme: jekyll-theme-cayman
google_analytics: UA-215798856-1
